


using System.Text;

namespace aoc25_day_06
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var input = ReadInput("input.txt");
            Solve(input);

            var inputP2 = ReadInputP2("input.txt");

            SolveP2(inputP2);
        }

        private static void SolveP2(List<Problem> input)
        {
            var newProblems = new List<Problem>();
            foreach (var problem in input)
            {
                var newProblem = tranformProblem(problem);
                newProblems.Add(newProblem);
            }

            Solve(newProblems);
        }

        private static Problem tranformProblem(Problem p)
        {
            Console.WriteLine("orginal");
            p.print();
            var numbers = new List<string>();
            for (int i = 0; i < p.numbers.Count - 1; i++) // BUG 1: < Count -2
            {
                numbers.Add(p.numbers[i]);
            }

            var realNumbers = new List<string>();
            var index = 0;
            while (true)
            {
                var n = "";
                // this for was generated by ai, also was my idea
                for (int i = 0; i < numbers.Count; i++)
                {
                    if (index < numbers[i].Length)
                    {
                        if (numbers[i][index] != ' ')
                        {
                            n += numbers[i][index];
                        }
                    }
                }

                // the annoying thing about the ai predictions in VS is
                // that you are confronted with totally wrong predictions
                // so often, it gets very annoying.
                // ok, sometimes it is good, but often it is just wrong and 
                // then it is a total distraction.
                // I think I will turn it off. <--- LOL this was ai predicting me writing this comment
                if (n == "")
                {
                    break;
                }
                realNumbers.Add(n);

                index++;
            }

            var result = new Problem();
            result.numbers = realNumbers;
            result.numbers.Add(p.numbers.Last().Trim());


            Console.WriteLine("transformed");
            result.print();
            return result;
        }

        private static void Solve(List<Problem> input)
        {
            long total = 0;
            foreach (var problem in input)
            {
                var operation = problem.numbers.Last();
                var result = long.Parse(problem.numbers.First());
                for (int i = 1; i < problem.numbers.Count-1; i++)
                {
                    var operand = long.Parse(problem.numbers[i]);
                    if (operation == "*")
                    {
                        result = result * operand;
                    }
                    else if (operation == "+")
                    {
                        result = result + operand;
                    }
                    else
                    {
                        throw new Exception("unknown operator");
                    }
                }
                total += result;
            }
            Console.WriteLine($"Grand total={total}");
        }

        private static List<Problem> ReadInput(string v)
        {
            var result = new List<Problem>();

            var lines = File.ReadAllLines(v);

            foreach (var line in lines)
            {
                var parts = splitLine(line);
                
                if (result.Count == 0)
                {
                    for (var i = 0; i < parts.Count; i++)
                    {
                        result.Add(new Problem());
                    }
                }

                for (var i = 0;i < parts.Count; i++)
                {
                    result[i].numbers.Add(parts[i]);
                }
            }

            return result;
        }

        private static List<Problem> ReadInputP2(string v)
        {
            var result = new List<Problem>();

            var lines = File.ReadAllLines(v);
            var operatorLine = lines.Last();
            var separatorColumns = new List<int>();
            for (int i = 0; i < operatorLine.Length; i++)
            {
                if (operatorLine[i] != ' ')
                {
                    separatorColumns.Add(i - 1);
                }
            }
            //separatorColumns.Add(operatorLine.Length); //BUG 2
            var newLines = new List<string>();
            foreach (var line in lines)
            {
                var templLine = new StringBuilder(line);
                foreach (var sep in separatorColumns)
                {
                    if (sep >= 0 && sep < templLine.Length)
                    {
                        templLine[sep] = '@';
                    }
                }
                newLines.Add(templLine.ToString());
            }

            foreach (var line in newLines)
            {
                var parts = splitLine2(line);

                if (result.Count == 0)
                {
                    for (var i = 0; i < parts.Count; i++)
                    {
                        result.Add(new Problem());
                    }
                }

                for (var i = 0; i < parts.Count; i++)
                {
                    result[i].numbers.Add(parts[i]);
                }

            }
            foreach (var problem in result)
            {
                problem.print();
            }

            return result;
        }

        private static List<string> splitLine(string line)
        {
            var result = new List<string>();

            var parts = line.Split(' ');

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    result.Add(part);
                }
            }
            return result;
        }
        private static List<string> splitLine2(string line)
        {
            var result = new List<string>();

            var parts = line.Split('@');

            foreach (var part in parts)
            {
                if (part.Length > 0)
                {
                    result.Add(part);
                }
            }
            return result;
        }
    }

    class Problem
    {
        public List<string> numbers = new();

        internal void print()
        {
            foreach (var item in numbers)
            {
                Console.WriteLine(item);
            }
            Console.WriteLine();
        }
    }
}
