
namespace aoc25_day_08
{
    /*
     * 1000 punten --> afstanden bepalen van elk punt naar een andere
     * 
     *
     *
     *
     */

    internal class Program
    {
        static void Main(string[] args)
        {
            P1();
            P2();
        }

        static void P2()
        {
            var boxes = ReadInput("input.txt");

            var boxPairs = CreateBoxPairs(boxes);

            //printBoxPairs(boxPairs);

            boxPairs.Sort((a, b) => a.Distance.CompareTo(b.Distance));

            var circuits = new List<Circuit>();
            foreach (var box in boxes)
            {
                var c = new Circuit();
                box.Circuit = c;
                c.boxes.Add(box);
                circuits.Add(c);
            }

            //printBoxPairs(boxPairs);

            var count = 0;
            var x = -1;
            while (true)
            {
                x++;
                var pair = boxPairs[x];


                if (pair.Box1.Circuit != pair.Box2.Circuit)
                {
                    // merge circuits generated by ai
                    var circuit1 = pair.Box1.Circuit;
                    var circuit2 = pair.Box2.Circuit;
                    // merge circuits
                    foreach (var box in circuit2.boxes)
                    {
                        box.Circuit = circuit1;
                        circuit1.boxes.Add(box);
                    }
                    circuits.Remove(circuit2);
                    Console.WriteLine($"circuits.count = {circuits.Count}");
                    if (circuits.Count == 1)
                    {
                        var result = pair.Box1.x * pair.Box2.x;
                        Console.WriteLine($"Product of X coords = {result}");
                        break;
                    }
                }
                count++;
                Console.WriteLine($"Count == {count}");
                //if (count == 1000)
                //{
                //    break;
                //}
            }


        }

        static void P1()
        {
            var boxes = ReadInput("input.txt");

            var boxPairs = CreateBoxPairs(boxes);


            //printBoxPairs(boxPairs);

            boxPairs.Sort((a, b) => a.Distance.CompareTo(b.Distance));

            var circuits = new List<Circuit>();
            foreach (var box in boxes)
            {
                var c = new Circuit();
                box.Circuit = c;
                c.boxes.Add(box);
                circuits.Add(c);
            }

            //printBoxPairs(boxPairs);

            var count = 0;
            var x = -1;
            while (true)
            {
                x++;
                var pair = boxPairs[x];


                if (pair.Box1.Circuit != pair.Box2.Circuit)
                {
                    // merge circuits generated by ai
                    var circuit1 = pair.Box1.Circuit;
                    var circuit2 = pair.Box2.Circuit;
                    // merge circuits
                    foreach (var box in circuit2.boxes)
                    {
                        box.Circuit = circuit1;
                        circuit1.boxes.Add(box);
                    }
                    circuits.Remove(circuit2);
                }
                count++;
                if (count == 1000)
                {
                    break;
                }
            }

            circuits.Sort((a, b) => b.boxes.Count.CompareTo(a.boxes.Count)); // sort descending AI ftw

            //printCircuits(circuits);

            var result = 1;
            // bizar, deze for werd zo door ai gegenereerd!!! nee 3 was eetst 4
            for (int i = 0; i < 3; i++)
            {
                result *= circuits[i].boxes.Count;
            }

            Console.WriteLine($"result = {result}");

        }

        private static void printCircuits(List<Circuit> circuits)
        {
            for (int i = 0; i < circuits.Count; i++)
            {
                var s = "";
                foreach (var b in circuits[i].boxes)
                {
                    s += b.AsString() + " ";
                }
                Console.WriteLine($"{circuits[i].boxes.Count} - {s}");
            }
        }

        private static void printBoxPairs(List<BoxPair> boxPairs)
        {
            for (int i = 0; i < boxPairs.Count; i++)
            {
                var bp = boxPairs[i];
                Console.WriteLine($"{bp.Box1.AsString()} - {bp.Box2.AsString()}: {bp.Distance}");
            }
        }

        private static List<BoxPair> CreateBoxPairs(List<JunctionBox> boxes)
        {
            // fully created by ai
            var boxPairs = new List<BoxPair>();
            for (int i = 0; i < boxes.Count-1; i++) // ai miste hier de -1
            {
                for (int j = i + 1; j < boxes.Count; j++)
                {
                    var boxPair = new BoxPair(boxes[i], boxes[j]);
                    boxPairs.Add(boxPair);
                }
            }
            return boxPairs;
        }

        private static List<JunctionBox> ReadInput(string v)
        {
            var boxes = new List<JunctionBox>();
            var lines = File.ReadAllLines(v);
            foreach (var line in lines)
            {
                var box = new JunctionBox(line);
                boxes.Add(box);
            }
            return boxes;
        }
    }

    class BoxPair
    {
        public JunctionBox Box1 { get; set; }
        public JunctionBox Box2 { get; set; }
        public double Distance { get; set; }
        public BoxPair(JunctionBox box1, JunctionBox box2)
        {
            Box1 = box1;
            Box2 = box2;

            double z = Math.Pow(box1.x - box2.x, 2) +
                       Math.Pow(box1.y - box2.y, 2) +
                       Math.Pow(box1.z - box2.z, 2);

            Distance = Math.Sqrt(z);
        }
    }

    class Circuit
    {
        public List<JunctionBox> boxes = new List<JunctionBox>();
    }

    class JunctionBox
    {
        public Circuit? Circuit { get; set; } = null;

        public int x;
        public int y;
        public int z;

        public JunctionBox(string line)
        {
            var parts = line.Split(',');
            x = int.Parse(parts[0]);
            y = int.Parse(parts[1]);
            z = int.Parse(parts[2]);
        }

        internal string AsString()
        {
            return $"({x},{y},{z})";
        }
    }
}
